Pin renovate to version `41.124.1`
Pinned the version to allow renovate to work again with cargo. The
following error started happening after `41.125.0` version:

```
error: failed to acquire package cache lock\n\nCaused by:\n  failed to
open: /home/ubuntu/.cargo/.package-cache\n\nCaused by:\n  failed to
create directory `/home/ubuntu/.cargo`\n\nCaused by:\n  File exists (os
error 17)\n
```

which in turn would fail to create any update PRs since the cargo
command fails to that error.

There is an open issue regarding this: https://github.com/renovatebot/renovate/issues/38378